---
version: '3.7'
services:
  zakupnik:
    container_name: zakupnik
    image: tborychowski/zakupnik
    restart: unless-stopped
    ports:
      - "3000:${PORT}"
    env_file:
      - ./.env
    volumes:
      - ./database.db:/app/database.db
