#! /bin/bash
mkdir icon

convert icon-round.png -resize 16x16 icon/favicon-16x16.png
convert icon-round.png -resize 32x32 icon/favicon-32x32.png
convert icon-square.png -resize 150x150 icon/mstile-150x150.png

convert icon-square.png -resize 180x180 icon/apple-touch-icon.png
convert icon-square.png -resize 60x60 icon/apple-touch-icon-60x60.png
convert icon-square.png -resize 76x76 icon/apple-touch-icon-76x76.png
convert icon-square.png -resize 120x120 icon/apple-touch-icon-120x120.png
convert icon-square.png -resize 152x152 icon/apple-touch-icon-152x152.png
convert icon-square.png -resize 180x180 icon/apple-touch-icon-180x180.png
convert icon-square.png -resize 192x192 icon/android-chrome-192x192.png
convert icon-square.png -resize 512x512 icon/android-chrome-512x512.png

convert icon-round.png -resize 180x180 icon/apple-touch-icon-precomposed.png
convert icon-round.png -resize 60x60 icon/apple-touch-icon-60x60-precomposed.png
convert icon-round.png -resize 76x76 icon/apple-touch-icon-76x76-precomposed.png
convert icon-round.png -resize 120x120 icon/apple-touch-icon-120x120-precomposed.png
convert icon-round.png -resize 152x152 icon/apple-touch-icon-152x152-precomposed.png
convert icon-round.png -resize 180x180 icon/apple-touch-icon-180x180-precomposed.png

echo Done!
